{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gantry.fullname" . }}
  labels:
    {{- include "gantry.labels" . | nindent 4 }}
type: Opaque
stringData:
  GANTRY_SERVER__APIKEY__SECRET: {{ .Values.secrets.apikey_secret | quote }}
  GANTRY_SERVER__KEYCLOAK__SERVICE_CLIENT_ID: {{ .Values.secrets.keycloak_service_client_id | quote }}
  GANTRY_SERVER__KEYCLOAK__SERVICE_CLIENT_SECRET: {{ .Values.secrets.keycloak_service_client_secret | quote }}
  GANTRY_SERVER__BILLING__STRIPE_SECRET_KEY: {{ .Values.secrets.billing_stripe_secret_key | quote }}
  GANTRY_SERVER__BILLING__STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.billing_stripe_webhook_secret | quote }}
  GANTRY_SERVER__FILE_STORAGE__S3_BUCKET_NAME: {{ .Values.secrets.file_storage_s3_bucket_name | quote }}
  GANTRY_SERVER__FILE_STORAGE__S3_REGION_NAME: {{ .Values.secrets.file_storage_s3_region_name | quote }}
  GANTRY_SERVER__FILE_STORAGE__S3_ACCESS_KEY_ID: {{ .Values.secrets.file_storage_s3_access_key_id | quote }}
  GANTRY_SERVER__FILE_STORAGE__S3_SECRET_ACCESS_KEY: {{ .Values.secrets.file_storage_s3_secret_access_key | quote }}
  GANTRY_SERVER__FILE_STORAGE__S3_ENDPOINT_URL: {{ .Values.secrets.file_storage_s3_endpoint_url | quote }}
  GANTRY_SERVER__RAG__EMBEDDING_OPENAI_API_KEY: {{ .Values.secrets.rag_embedding_openai_api_key | quote }}
  GANTRY_SERVER__RAG__RERANKER_API_KEY: {{ .Values.secrets.rag_reranker_api_key | quote }}
{{- end }}
