{{- if and .Values.config.observability (eq .Values.config.observability.metrics "prometheus") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gantry.fullname" . }}
  labels:
    {{- include "gantry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gantry.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: internal
      path: /metrics
      interval: 30s
{{- end }}
