apiVersion: v1
kind: Service
metadata:
  name: {{ include "gantry.fullname" . }}
  labels:
    {{- include "gantry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.internalPort }}
      targetPort: internal
      protocol: TCP
      name: internal
  selector:
    {{- include "gantry.selectorLabels" . | nindent 4 }}
